# -*- coding: utf-8 -*-
"""Vassar

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19ZGi4jqRE8KDAnyVNJYHGDAbDkIpUrNr
"""

import numpy
import pandas

import requests
print ('requests is working')

!git --version

